
name: Generate snake animation



on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"



  # Allow manual triggering of the workflow

  workflow_dispatch:



  # Trigger the workflow on pushes to the main branch

  push:

    branches:

       - master



jobs:

   generate:
    permissions:
      contents: write
  

    runs-on: ubuntu-latest

    timeout-minutes: 5



    steps:

    - name: generate snake.gif
      uses: Platane/snk/gif-only@v3
          

      with:
       
         github_user_name: ${{ github.repository_owner }}
         outputs: dist/snake.gif?palette=github-dark


    - name: push snake.svg to the output branch
      uses: crazy-max/ghaction-github-pages@v3.1.0
        
      with:
          target_branch: output
          build_dir: dist

        

      env:

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



          commit_message: "Update snake animation [skip ci]"
